#!/bin/bash

# ==================== Home or Beam Server ====================
# HDF5 pathe (correct if you need)

if [[ "${1,,}" == "beam" ]]; then
   # For Beam Server
   HDF5_INCLUDE="/opt/hdf5/1.14.5/include"
   HDF5_LIB="/opt/hdf5/1.14.5/lib"

   # MPI path
   MPICXX="/opt/ompi/5.0.6/bin/mpicxx"

else
   # For Home computer
   HDF5_INCLUDE="/usr/include/hdf5/openmpi"
   HDF5_LIB="/usr/lib/x86_64-linux-gnu/hdf5/openmpi"

   # MPI path
   MPICXX="/usr/bin/mpicxx"

fi

# =====================================================

# compile option
CFLAGS="-I${HDF5_INCLUDE} -O3 -march=native -mtune=native -Wall -std=c++17 -ffast-math"
LDFLAGS="-L${HDF5_LIB} -lhdf5 -lhdf5_hl -lz -ldl -lm"

# ==================== start build ====================

echo "=== FEL codes (C++) 빌드 시작 ==="

# felParticle build
echo "Building felParticle..."
${MPICXX} -o felParticle felParticle.cpp ${CFLAGS} ${LDFLAGS}
echo "'felParticle' is made."

# felField build
echo "Building felField..."
${MPICXX} -o felField felField.cpp ${CFLAGS} ${LDFLAGS}
echo "'felField' is made."

